version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/sledge
hooks:
  AfterInstall:
    - location: scripts/run_build.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/reload_server.sh
      timeout: 60
      runas: root
