name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install system dependencies
        run: sudo apt-get install nodejs yarn
      - name: Install node_modules dependencies
        run: yarn install
      - name: Build using Makefile
        run: make build
      - name: Run with --initonly flag
        run: ./bin/sledge --initonly
      - name: Run jest tests
        run: ./node_modules/.bin/jest