name: Run Jest tests on server endpoints

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install server dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test
