name: Run Jest tests on server endpoints

on: [push]

jobs:
  setup and test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017

    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install server dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test
