# This workflow will automatically test feature branches. Functionality first, quality can come later :P

name: Code Functionality Assurance

on:
  push:
    branches-ignore:
      - env/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-endpoints:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017

    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install server dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test
